# Generated by Django 4.2.16 on 2024-12-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_rename_titulo_photo_title_photo_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='imagen',
            new_name='image',
        ),
    ]
