# Generated by Django 4.2.16 on 2024-12-06 06:51

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_rename_imagen_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='reduced_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=photos.models.album_upload_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
